//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.29 at 09:05:39 PM BRT 
//


package com.cartorio.valkyria.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for decodificaReciboResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="decodificaReciboResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="reciboDecodificado" type="{http://www.tjsc.jus.br/selo}reciboProtocolo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "decodificaReciboResponse", propOrder = {
    "reciboDecodificado"
})
public class DecodificaReciboResponse {

    protected ReciboProtocolo reciboDecodificado;

    /**
     * Gets the value of the reciboDecodificado property.
     * 
     * @return
     *     possible object is
     *     {@link ReciboProtocolo }
     *     
     */
    public ReciboProtocolo getReciboDecodificado() {
        return reciboDecodificado;
    }

    /**
     * Sets the value of the reciboDecodificado property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReciboProtocolo }
     *     
     */
    public void setReciboDecodificado(ReciboProtocolo value) {
        this.reciboDecodificado = value;
    }

}
