//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.01 at 11:21:42 PM BRT 
//


package com.cartorio.valkyria.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for especieTitulo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="especieTitulo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cdespecietitulo" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/&gt;
 *         &lt;element name="nmespecietitulo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sgespecietitulo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "especieTitulo", propOrder = {
    "cdespecietitulo",
    "nmespecietitulo",
    "sgespecietitulo"
})
public class EspecieTitulo {

    protected Short cdespecietitulo;
    protected String nmespecietitulo;
    protected String sgespecietitulo;

    /**
     * Gets the value of the cdespecietitulo property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCdespecietitulo() {
        return cdespecietitulo;
    }

    /**
     * Sets the value of the cdespecietitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCdespecietitulo(Short value) {
        this.cdespecietitulo = value;
    }

    /**
     * Gets the value of the nmespecietitulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmespecietitulo() {
        return nmespecietitulo;
    }

    /**
     * Sets the value of the nmespecietitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmespecietitulo(String value) {
        this.nmespecietitulo = value;
    }

    /**
     * Gets the value of the sgespecietitulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSgespecietitulo() {
        return sgespecietitulo;
    }

    /**
     * Sets the value of the sgespecietitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSgespecietitulo(String value) {
        this.sgespecietitulo = value;
    }

}
